name: MonLab
mgmt:
    network: MonLab-mgmt
    ipv4-subnet: 172.20.20.0/24
topology:
    kinds:
        ceos:
            image: arista/ceos:4.30.3M
    nodes:
        Leaf1a:
            kind: ceos
            mgmt-ipv4: ""
            env:
                CLAB_MGMT_VRF: ""
        Leaf1b:
            kind: ceos
            mgmt-ipv4: ""
            env:
                CLAB_MGMT_VRF: ""
        Leaf2a:
            kind: ceos
            mgmt-ipv4: ""
            env:
                CLAB_MGMT_VRF: ""
        Leaf2b:
            kind: ceos
            mgmt-ipv4: ""
            env:
                CLAB_MGMT_VRF: ""
        Spine1:
            kind: ceos
            mgmt-ipv4: ""
            env:
                CLAB_MGMT_VRF: ""
        Spine2:
            kind: ceos
            mgmt-ipv4: ""
            env:
                CLAB_MGMT_VRF: ""
        Spine3:
            kind: ceos
            mgmt-ipv4: ""
            env:
                CLAB_MGMT_VRF: ""
    links:
        - endpoints: ['Spine1:eth2', 'Leaf1a:eth2']
        - endpoints: ['Spine1:eth3', 'Leaf1b:eth2']
        - endpoints: ['Spine1:eth4', 'Leaf2a:eth2']
        - endpoints: ['Spine1:eth5', 'Leaf2b:eth2']
        - endpoints: ['Spine2:eth2', 'Leaf1a:eth3']
        - endpoints: ['Spine2:eth3', 'Leaf1b:eth3']
        - endpoints: ['Spine2:eth4', 'Leaf2b:eth3']
        - endpoints: ['Spine3:eth2', 'Leaf1b:eth4']
        - endpoints: ['Spine3:eth3', 'Leaf1a:eth4']
        - endpoints: ['Leaf1a:eth5', 'Leaf1b:eth5']
        - endpoints: ['Leaf1b:eth6', 'Leaf1a:eth6']
        - endpoints: ['Leaf2a:eth3', 'Leaf2b:eth4']
        - endpoints: ['Leaf2b:eth5', 'Leaf2a:eth4']
        - endpoints: ['Spine2:eth5', 'Leaf2a:eth5']
        - endpoints: ['Spine3:eth4', 'Leaf2b:eth6']
        - endpoints: ['Spine3:eth5', 'Leaf2a:eth6']
