name: exampleLab
mgmt:
    network: exampleLab-mgmt
    ipv4-subnet: 172.20.20.0/24
topology:
    kinds:
        ceos:
            image: arista/ceos:4.30.3M
            binds:
                - ./cv-onboarding-token:/mnt/flash/cv-onboarding-token
    nodes:
        Leaf1:
            kind: ceos
            mgmt-ipv4: 172.20.20.4
            env:
                CLAB_MGMT_VRF: MGMT
            binds:
                - configs/ceos-config/Leaf1.cfg:/mnt/flash/ceos-config:ro
        Leaf2a:
            kind: ceos
            mgmt-ipv4: 172.20.20.5
            env:
                CLAB_MGMT_VRF: MGMT
            binds:
                - configs/ceos-config/Leaf2a.cfg:/mnt/flash/ceos-config:ro
        Leaf2b:
            kind: ceos
            mgmt-ipv4: 172.20.20.6
            env:
                CLAB_MGMT_VRF: MGMT
            binds:
                - configs/ceos-config/Leaf2b.cfg:/mnt/flash/ceos-config:ro
        Leaf3a:
            kind: ceos
            mgmt-ipv4: 172.20.20.7
            env:
                CLAB_MGMT_VRF: MGMT
            binds:
                - configs/ceos-config/Leaf3a.cfg:/mnt/flash/ceos-config:ro
        Leaf3b:
            kind: ceos
            mgmt-ipv4: 172.20.20.8
            env:
                CLAB_MGMT_VRF: MGMT
            binds:
                - configs/ceos-config/Leaf3b.cfg:/mnt/flash/ceos-config:ro
        Spine1:
            kind: ceos
            mgmt-ipv4: 172.20.20.2
            env:
                CLAB_MGMT_VRF: MGMT
            binds:
                - configs/ceos-config/Spine1.cfg:/mnt/flash/ceos-config:ro
        Spine2:
            kind: ceos
            mgmt-ipv4: 172.20.20.3
            env:
                CLAB_MGMT_VRF: MGMT
            binds:
                - configs/ceos-config/Spine2.cfg:/mnt/flash/ceos-config:ro
    links:
        - endpoints: ['Leaf1:eth1', 'Spine1:eth1']
        - endpoints: ['Leaf1:eth2', 'Spine2:eth1']
        - endpoints: ['Leaf2a:eth1', 'Spine1:eth2']
        - endpoints: ['Leaf2a:eth2', 'Spine2:eth2']
        - endpoints: ['Leaf2a:eth3', 'Leaf2b:eth1']
        - endpoints: ['Leaf2b:eth2', 'Spine1:eth3']
        - endpoints: ['Leaf2b:eth3', 'Spine2:eth3']
        - endpoints: ['Leaf3a:eth1', 'Spine1:eth4']
        - endpoints: ['Leaf3a:eth2', 'Spine2:eth4']
        - endpoints: ['Leaf3b:eth1', 'Spine1:eth5']
        - endpoints: ['Leaf3b:eth2', 'Spine2:eth5']
        - endpoints: ['Leaf3a:eth3', 'Leaf3b:eth3']
